### ISSUE TITLE
Team

### ISSUE THREAD

**Issue by sokra** [webpack/analyse-tool#1]
I'm looking for a new team of developers/designers that want to write a new analyse tool.

It should feature a web-based version and an electron version. You are free to choose the tooling with the team, I would recommend webpack, ES6, React.js, [react-router](https://github.com/rackt/react-router), [CSS Modules](https://github.com/css-modules/css-modules), [react-toolbox](https://github.com/react-toolbox/react-toolbox), [Redux](https://github.com/rackt/redux).

You can see it as chance to work with bleeding egde technologies and contribute to OSS. It propably also give a depther understanding of the webpack compilation and optimization options. I hope this results in a tool that helps everybody to analyse and optimize their webpack build.

Of couse the tool would feature your and/or your company's name at some place.

**Comment by made-by-chris** [comment]
Can your write more about the potential benefits for participants, and required levels of experience? 
I'm a junior web 'jack of all trades', just working out the ins and outs of webpack for myself over the last couple weeks.

**Comment by toxicFork** [comment]
What exactly would you analyse though?

**Comment by bebraw** [comment]
@toxicFork Webpack stats. See [Webpack Chart](https://alexkuz.github.io/webpack-chart/) by @alexkuz, [Webpack Visualizer](https://chrisbateman.github.io/webpack-visualizer/) by @chrisbateman, and [the original analyse tool](https://webpack.github.io/analyse/) by @sokra for ideas.

**Comment by toxicFork** [comment]
oh yeah I remember using these for optimization, will follow this :+1:

**Comment by sokra** [comment]
> Can your write more about the potential benefits for participants

I can't offer any financial benefits. It's an open source project. But you may get:
- experiance working in a team, on an open source project, with new technologies
- interesting discussions with other team members
- as member of the webpack you can show the webpack icon in your github profile
- better understanding of the webpack compilation and optimization options

> and required levels of experience?

If you feel able to do this you can take part. The team will decide for team leaders, which are resposible for reviewing and merging PRs into the master branch. Every change will occur on feature branches.

So if you are not sure if you experience is enough you can still contribute and be sure that your will be reviewed. Maybe it's also a chance to learn from other contributors.

> See Webpack Chart by @alexkuz, Webpack Visualizer by @chrisbateman, and the original analyse tool by @sokra for ideas.

I really hope to get you into the team so we can make one awesome tool.

**Comment by zaggy** [comment]
Hi, would be more than happy to join this project. I have not much experience in open source projects, but would be more than happy to help my favorite webpack with what I am capable of.

**Comment by corintho** [comment]
> It should feature a web-based version and an electron version. You are free to choose the tooling with the team, I would recommend webpack, ES6, React.js, CSS Modules, react-toolbox, Redux.

The proposed tooling is exactly what I am starting to use on the place I work, and it is an awesome combination. I only lack experience with electron, and right now this seems an excellent opportunity to close that gap and get a better understanding of webpack internals at the same time.

Count me in.

**Comment by abd124abd** [comment]
Hi, I'd love to join this project.  Still learning but have been playing a lot with this specific line-up of tooling and would be very interested in contributing in any way as part of a team.

**Comment by alexkuz** [comment]
I'd love to help! (if I'll have a time). 

(@gaearon, are you in?)

**Comment by chrisbateman** [comment]
I'd love to contribute.

**Comment by sokra** [comment]
I'm pretty happy to see you all interested :smile:

**Comment by mattiaocchiuto** [comment]
I'm very interested in joining the project, I've no experience in open source projects but I think this could be a very good starting point for me!

**Comment by dlmr** [comment]
This sounds fun and interesting, I would love to contribute.

**Comment by noomorph** [comment]
+1, i'm in.

**Comment by mmw** [comment]
I'd love to help anyway I can

**Comment by timaschew** [comment]
I'd love to help out. I have experience in some open source projects, on of them was [component](https://github.com/componentjs/component), it's deprecated now, but maybe we can get some new ideas out of it.

**Comment by gaearon** [comment]
I'm busy with other projects but I'll be happy to keep an eye on it and maybe lend a hand at reviewing Redux-related parts of code if you decide to use it.

**Comment by luqin** [comment]
:+1:

**Comment by sergey-lapin** [comment]
I will gladly participate in this!

**Comment by bartekus** [comment]
I'm currently looking at kriasoft's react-starter-kit which currently has the best(overall, not all-around) webpack implementation that I've seen so far and while I'm modifying it to redux I figure I could be of some help to you guys

**Comment by alajmo** [comment]
I'd gladly help as well, has there been any official / inofficial teamleader as of so far?

**Comment by sokra** [comment]
> has there been any official / inofficial teamleader as of so far?

not yet, but I'll open an issue today, where candiates can apply, or be proposed.

**Comment by msuntharesan** [comment]
I am willing to help. I don't have much experience in contributing to OSS project. This will be a learning experience for me on that.
- I've used webpack, babel.
- I have done projects using react, redux
- Played with react-toolbox (mostly peek inside the source)

**Comment by drew** [comment]
I'd like to offer my help. My last OSS contribution was several years ago during a GSoC project. I currently use React, ES6, Webpack and React Router in production at my day job.

**Comment by louy2** [comment]
Sounds like a perfect chance to learn a lot. I am using React+Redux+Babel+Express at work, and I desperately need more knowledge on how to better manage this combination. May I join?

**Comment by saiberz** [comment]
Am i too late to join the project?  I'd like to help if it's possible , i've been working with React,Webpack, ES6 and Redux :)

**Comment by sokra** [comment]
Of course not. We are always happy with more people helping...

**Comment by manekinekko** [comment]
@sokra are u still looking for members ?

**Comment by bartekus** [comment]
I've been working with the meatier development which I intend to utilize to showcase the full potential of the analyze-tool fyi, incase anybody wonders what's going on in this side of the camp.
